### ISSUE TITLE
Potential open file limit problem with macOS or large 10X runs

### ISSUE THREAD

**Issue by Shians** [campbio/scruff#106]
Early on in scPipe we had a similar strategy of creating one file per cell, this turned out to be problematic on macOS machines as the open file limit on the default terminal is only 256. On iTerm2 it is 4864 and I think in the default Ubuntu terminal it is 4096.

I haven't looked too deeply into your file handling strategy, just wanted to give you an early warning of the potential problem. If at any time your package tries to access over the file limit, at least on macOS, it will silently deny you access and potentially cause silent bugs.

**Comment by zhewa** [comment]
Hi @Shians,

Thank you so much for your comment. It seems the file I/O restrictions on operating systems are a limiting factor for creating multiple cell-specific output files. We will keep that in mind during the development of the scruff package.
