### ISSUE TITLE
Error for wrong Cellranger barcode file

### ISSUE THREAD

**Issue by joshua-d-campbell** [campbio/scruff#128]
If someone uses the wrong barcode file, then the error given is:

```
Error in as.data.frame.default(x, ...) :
  cannot coerce class 'c("remote_error", "bperror", "error", "condition")' to a data.frame
```

which isn't very clear. Is there a way to determine that the cell barcodes are not matching and give a more informative error?

**Comment by zhewa** [comment]
#131
