### ISSUE TITLE
Error in if (ncol(sce) != length(cellPerWell) & length(cellPerWell) !=  :    argument is of length zero

### ISSUE THREAD

**Issue by parichitran** [campbio/scruff#184]
Greetings, I have a CEL-seq data incorpatated with umi.The following are the details of my reads
Reads were already demultiplexed to indivdual cell Fastq reads
READ-1 =8bp(cell barcode)+5bp(umi)
READ-2= (47bp)
Lets say if allign this Fastq and created a BAM file.How i can get deduplicated umi counts with scruff.
My case i also needed a deduplicated BAM file too.

I already tried to count umi using my BAM file genrated from STAR alligner i got the above error

**Comment by zhewa** [comment]
Hi @parichitran 
Suppose you have a vector called `PATH_TO_FASTQ` in R that contains the paths to individual demultiplexed FASTQ files, and a variable called `PATH_TO_GTF` which is the path to Rsubread index. The minimal command to generated BAM files and a count matrix would be:

```
library(SingleCellExperiment)
library(scruff)

sce <- SingleCellExperiment(colData = DataFrame(fastq_path = PATH_TO_FASTQ))

scealign <- alignRsubread(sce, index = PATH_TO_RSUBREAD_INDEX)
scecount <- countUMI(scealign, reference = PATH_TO_GTF)
```
